---

- name: "Cleanup & Destroy ForgeOps"
  hosts: localhost
  become: false
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    dev_dir: '{{ dev_home_dir }}'
    forgeops_dir: "{{ dev_dir }}/forgeops"
    namespace_name: '{{ namespace }}'

  tasks:
    - name: Set Up Your Local Computer to Use Minikube’s Docker Engine
      shell: eval $(minikube docker-env)
      register: "output"

    - name: "Shutdown and delete from namespace"
      command: "skaffold delete"
      args:
        chdir: "{{ forgeops_dir }}"
      register: "output"
    - debug: var=output.stdout_lines

    - name: "Delete persistant volume claims (PVC) from namespace"
      command: kubectl delete pvc --all
      args:
        chdir: "{{ forgeops_dir }}"
      register: "output"

    - debug: var=output.stdout_lines
 