---
# Shutdown and delete from namespace

- name: "Shutdown and delete from namespace"
  hosts: localhost
  become: false
  vars:
    namespace_name: my-namespace
    dev_dir: /Users/btumy/dev
    forgeops_dir: "{{ dev_dir }}/forgeops"
  connection: local
  
  tasks:
    - name: Shutdown and delete from namespace
      command: "skaffold delete"
      args:
        chdir: "{{ forgeops_dir }}"
      register: "output"
    
    - debug: var=output.stdout_lines

    - name: "Delete persistant volume claims (PVC) from namespace"
      command: "kubectl delete pvc --all"
      args: 
        chdir: "{{ forgeops_dir }}"
      register: "output"
    
    - debug: var=output.stdout_lines

