---
# You can run this playbook like this:  ansible-playbook -i ./hosts install_forgeops.yml\

- name: "Install and configure forgeops"
  hosts: localhost
  become: false
  connection: local
  vars:
    # change this to match your environment 
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    dev_dir: '{{ dev_home_dir }}'
    forgeops_dir: "{{ dev_dir }}/forgeops"
    forgeops_repo_url: '{{ forgeops_url }}'
    brew_cask_packages:
      - docker
      - virtualbox
    brew_packages:
      - kubernetes-cli
      - skaffold
      - kustomize
      - kubectx
      - minikube
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false 
    namespace_name: '{{ namespace }}'
  
  pre_tasks:
    - include: pre_tasks.yml
  
  tasks:
    - include: minikube_setup.yml
    - include: deploy_forgeops.yml