---
# You can run this playbook like this:  ansible-playbook -i ./hosts install_forgeops.yml\

- name: "Install and configure forgeops"
  hosts: localhost
  become: false
  vars:
    # change this to match your environment 
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    dev_dir: /Users/bradtumy/develop
    forgeops_dir: "{{ dev_dir }}/forgeops"
    forgeops_repo_url: https://github.com/ForgeRock/forgeops.git
    brew_cask_packages:
      - docker
      - virtualbox
    brew_packages:
      - kubernetes-cli
      - skaffold
      - kustomize
      - kubectx
      - minikube
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false 
    namespace_name: my-namespace
  connection: local

  pre_tasks:
    - include: pre_tasks.yml
  
  tasks:
    # - include: homebrew_tasks.yml
    - include: clone_forgeops_repo.yml
    - include: minikube_setup.yml
    - include: deploy_forgeops.yml